config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources :users, only: [:index]
  resources :categories, only: [:index, :new, :create, :show] do
    resources :records, only: [:index, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can(:manage, Category, user:)
    can :manage, Record, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :icon
  has_many :category_records
  has_many :records, through: :category_records

  validates :name, presence: true, length: { maximum: 250 }

  def recent_records
    records.order(created_at: :DESC)
  end

  def recent_categories
    categories.order(created_at: :DESC)
  end
end

app/models/category_record.rb
class CategoryRecord < ApplicationRecord
  belongs_to :category
  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :category_records
  has_many :categories, through: :category_records

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { greater_than: 0 }

  def total_price
    records.sum('amount')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :records

  validates :name, presence: true, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) ||
      if resource.is_a?(User)
        categories_path
      else
        super
      end
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.includes(:records).order(id: :desc)
  end

  def new; end

  def create
    add_category = current_user.categories.new(category_params)

    if add_category.save
      redirect_to '/categories', notice: 'Category Added!'
    else
      render :new, alert: 'Failed to add category'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  load_and_authorize_resource

  def index
    @category = current_category
  end

  def new; end

  def create
    @record = current_user.records.new(record_params)
    if @record.save
      redirect_to category_records_path(current_category), notice: 'You completed this transaction successfully'
    else
      render :new, alert: 'New transaction could not be created.'
    end
  end

  def current_category
    @categories = current_user.categories.includes(:records).find(params[:category_id])
  end

  private

  def record_params
    params.require(:record).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div>
  <%= render partial: "partials/navbar", locals: {variable: 'CATEGORIES', path: root_path } %>
</div>

<section class="home">
  <ul class="categories">
    <% @categories.each do |category| %>
      <li class="card mt-3 category">
        <%= image_tag(category.icon, class: "icons") %>
        <div>
          <h3>
            <%= link_to category.name, category_records_path(category.id), class: "catLink" %>
          </h3>
          <p>Total: NGN <%= category.records.reduce(0) { |sum, item| sum + item.amount } %></p>
        </div>
      </li>
    <% end %>
  </ul>
</section>
<div class="addButton mt-2">
  <%= link_to "Add a new category", new_category_path, class: "addBtn"%>
</div>

app/views/categories/new.html.erb
<section class="login">
  <%= form_with model: @categories, url:categories_path, scope: :category, method: :post, data: { turbo: false }, class: "form" do |form| %>
    <div class="nav">
      <%= link_to categories_path do %>
        <i class="fa-solid fa-arrow-left back"></i>
      <% end %>
      <div>
        ADD A NEW CATEGORY
      </div>
      <div class="actions">
        <%= form.submit "ADD", class: "loginBtn" %>
      </div>
    </div>
  
    <%= render partial: "devise/shared/notification" %>

    <div class="textField mt-3 md-3 row g-1">
      <div class="field">
        <%= form.text_field :name, placeholder: "Category name", autofocus: true, autocomplete: "name", class: "form-control stuff" %>
      </div>

      <div class="field">
        <%= form.file_field :icon, placeholder: "Icon", class: "form-control stuff" %>
      </div>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetWise App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Italianno&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Italiana&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/29d7bf5b00.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/9ef5f4f831.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", data: {turbo_track: :reload} %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="nav">
  <%= link_to path do %>
        <i class="fa-solid fa-arrow-left back"></i>
      <% end %>
  <div> <%= variable %> </div>
  <div>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "loginBtn" %>
  </div>
</nav>

<%= render partial: "devise/shared/notification" %>

app/views/records/index.html.erb
<div>
  <%= render partial: "partials/navbar", locals: {variable: 'TRANSACTIONS', path: categories_path } %>
</div>
<div class="card flex-row justify-content-between align-items-baseline">
  <h5 class="catLink category mt-3 mb-3">Total Amount: </h5>
  <h6>NGN <%= @category.recent_records.reduce(0) { |sum, item| sum + item.amount } %></h6>
</div>
<section class="home">
  <ul class="categories">
    <% @category.recent_records.each do |record| %>
      <li class="card mt-3 p-2">
        <div class="d-flex justify-content-between align-items-baseline">
          <h3 class="catLink">
            <%= record.name %>
          </h3>
          <h5>NGN <%= record.amount %></h5>
        </div>
        <hr/>
        <%= record.created_at.strftime("%d %b %Y") %>
      </li>
    <% end %>
  </ul>
</section>
<div class="addButton mt-2">
  <%= link_to "Add a new transaction", new_category_record_path, class: "addBtn"%>
</div>

app/views/records/new.html.erb
<section class="login">
  <%= form_with model: @category_records, url:category_records_path, scope: :record, method: :post, data: { turbo: false }, class: "form" do |form| %>
    <div class="nav">
      <%= link_to category_records_path do %>
        <i class="fa-solid fa-arrow-left back"></i>
      <% end %>
      <div>
        GOT A NEW TRANSACTION?
      </div>
      <div class="actions">
        <%= form.submit "ADD", class: "loginBtn" %>
      </div>
    </div>
    <div class="textField mt-3 md-3">
      <div class="field">
        <%= form.text_field :name, placeholder: "Transaction name", autofocus: true, autocomplete: "name", class: "form-control stuff" %>
      </div>

      <div class="field">
        <%= form.text_field :amount, placeholder: "Amount", autofocus: true, autocomplete: "email", class: "form-control stuff" %>
      </div>

      <div class="general-checkbox-div card p-3 align-items-start">
        <%= form.label :categories, 'Select Category/Categories', class: 'checkbox-main-label options' %><br>
        <%= form.collection_check_boxes :category_ids, Category.where(user_id: current_user.id), :id, :name, class: '' do |cat| %>
          <div class="checkbox-div">
            <%= cat.check_box %>
            <%= cat.label class: 'checkbox-label options' %><br>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</section>

app/views/users/index.html.erb
<section class="splash container">
  <h1>BudgetWise 💰</h1>
  <%= render partial: "devise/shared/notification"%>
  <div class="regBtns">
    <%= link_to "LOG IN", new_user_session_path, data: {turbo: false}, class: "btn btn-primary mb-1" %>
    <%= link_to "SIGN UP", new_user_registration_path, data: {turbo: false}, class: "btn" %>
  </div>
</section>